### ISSUE TITLE
Hashed credential [password] did not match.

### ISSUE THREAD

**Issue by felipepastor** [MrJuliuss/syntara#121]
Hi there,

I'm changing the app's environment and i've done a data tranfer from my dev db to prod db,  everything  i think is ok, but when i try to log in syntara gives me an error, so i needed to debug, and the RunTimeException is that: 
"A user was found to match all plain text credentials however hashed credential [password] did not match."

I've started to search a solution for this trouble, and discovered it's a sentry Exception. I've tried to change the hash in app/config/packages/cartalyst/sentry/config.php and nothing, i don't know why its occurs.

Can you guys help me? Thanks.

Just updating, i need to create another user with the command "php artisan create:user" to access the application.

**Comment by kk01011** [comment]
I' ve created a modular application in laravel framework and i'm using sentry for authentication. but after creating modules when i login with wrong credentials, i get this error "A user was found to match all plain text credentials however hashed credential [password] did not match."

before creating modular app..it was working fine...

Can you guys help me? Thanks
