### ISSUE TITLE
[HELP] Extending App

### ISSUE THREAD

**Issue by caloyz** [MrJuliuss/syntara#165]
Thank you for this great system, and for the continuous update and support. I current have a problem and it think its kind of a stupid question but when i extend the app as seen on http://mrjuliuss.github.io/syntara/docs/custom.html . Im quite confused as to where i should add the codes. in the part of:
"You must extend your new controller with the Syntara BaseController, like this :"  - i added the code in C:\wamp\www\formalistics\app\controllers\HomeController.php 

"To find your current loggued user, you need to add the basicAuth filter to your route :" - this one in 
C:\wamp\www\formalistics\app\routes.php

"HomeController getIndex view :" - for this one i have create index.blade.php and added it here
C:\wamp\www\formalistics\app\views\index.blade.php

the problem is it isnt working. theres no "my new feature" on the dashboard. maybe somethings wrong with the way i added the codes, Thank you for your help and more coding power..

**Comment by MrJuliuss** [comment]
Hi, your new feature does not appear on the dashboard. You need to extend the header and add your link.
