### ISSUE TITLE
When installing Permissions table missing and permission itself

### ISSUE THREAD

**Issue by mayarodina** [MrJuliuss/syntara#166]
After executing this command:
php artisan create:user username email password Admin

Laravel instantly pops up a whoops error stating that the table "Permissions" does not exist. Then I manually created it on phpmyadmin. This command above will leave the field "Permissions" in the Users table empty. As a consequence of that, when you go the Dropdown menu (Users, groups, permissions) on the Dashboard and select permissions, you will find a blank page. You need to insert a json formatted permission in the blank cell in the Users table so that the Blade Interface page for Permission can be displayed when selecting Permissions from that dropdown menu. These were the issues I encountered. It would be nice to have a simple but complete example of how to code in the controllers and the models those permissions and groups, since the sentry documentation does not do it.

2) When I create a new user, and I select a Permissons out of the select list, this does not get assigned to the user.  This is due to that original error where the permissions table is not created by default at Sentry, so the Syntara does not seem to address that issue. The checkboxes to assign groups work, they assign user and group to the users_group table.

Merci

**Comment by MrJuliuss** [comment]
Hi, this command `php artisan syntara:install` will create the Permission table. You need to launch this command before creating the user.
