### ISSUE TITLE
Bug in user activation by admin

### ISSUE THREAD

**Issue by shojibflamon** [MrJuliuss/syntara#176]
When admin activate user from all user list nothing happens
you can see put request from console panel

**Comment by shojibflamon** [comment]
in user.js 
find 
   "url": window.location.href.toString()+'/../user/'+userId+'/activate/',

replace
   "url": window.location.href.toString()+'/../user/'+userId+'/activate',

**Comment by MrJuliuss** [comment]
Hi, it works fine on my syntara (1.2.10)...

**Comment by shojibflamon** [comment]
but when i activate user from admin in console panel i just see : 
http://localhost/dashboard/user/4/activate
but my actual link should be : 
http://localhost/laravel/laravel-media/public/dashboard/users?page=1/../user/4/activate

when i cut last slah (/) it works fine.

**Comment by shojibflamon** [comment]
Same Problem happens when i activate user in pagination like ?page=2
there is nothing
it should look like 

            "type": "PUT",
            "url": window.location.href.toString().split('?')[0]+'/../user/'+userId+'/activate',
            "data": {userId : userId},
            "dataType": "json"

please update and notify me

thanks

**Comment by MrJuliuss** [comment]
Hi, could you try with this fix ? https://github.com/MrJuliuss/syntara/commit/800d0d87c881f43d89c61a00e777d41e811cf70e

Remove the slash '/' should no have impact : work fine on my syntara, only the activation is broken if i'm on a page > 1
