### ISSUE TITLE
Use different route for user login/register/forgot/edit

### ISSUE THREAD

**Issue by RokSiEu** [MrJuliuss/syntara#81]
Hi MrJuliuss, after long time I had to create project from start and I've forgot where I can change routes because now when my route is protected with basicAuth it gets redirected to localhost/project/public/dashboard/login . What I want is that user (from front end) will login through localhost/project/public/user/login . Because this will have different views than dashboard. (without dashboard, because that route will be for admins only).
Any suggestions?

In my front end user will have options to register,login,edit profile, send forgotten password. All this has to be accessible through localhost/project/public/user/login (register,forgot,edit etc). 

localhost/project/public/dashboard will still be accessible but only to admins or specific groups

**Comment by bkrajendra** [comment]
Can you help me with registration controller. I want to add public registration, forgot password etc. how to do it.?
